### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-healpix#111]
@lpsinger brought up the question whether to drop Python 2 support for `astropy-healpix` in https://github.com/astropy/astropy-healpix/pull/110#issuecomment-434522403

Let's discuss this separately, here.

It would help make `astropy-healpix` development simpler, in the C interfacing and possibly also in the Python code or API there are things that could be improved if we require Python 3.5+ or 3.6+ and dropped Python 2.7 support.

It also makes sense from the perspective that we work towards having this package in `astropy.healpix` in the core, since Astropy core has already dropped Python 2 support.

From the Gammapy perspective, it's a bit tricky. We are still supporting Python 2.7 because the Fermi ST don't support Python 3 yet. We don't use `astropy-healpix` yet, but since `regions` and `reproject` now depend on `astropy-healpix`, and we do use those, really if `astropy-healpix` drops Python 2 support, it'll become hard to keep supporting it, we would have to pin to older versions of `regions` and `reproject`.

@astrofrog - Thoughts? Would you be OK to drop Python 2.7 support in `astropy-healpix`, `reproject` and `regions` now?

@tboch - Thoughts?

hipspy is another package I'm aware of using `astropy-healpix`, but it was Python 3.6+ from the start, so OK to drop Python 2 support here.

**Comment by astrofrog** [comment]
If we drop support for Python 2.7 in master, it doesn't mean we couldn't still fix critical bugs in the v0.3.x branch (which would remain Python 2.7-compatible). So from my perspective, dropping Python 2 is fine. For now I'll make sure reproject work fine with the v0.3.x branch as well as future releases, so I don't think you need to worry about pinning versions of reproject and regions for now. Python 2 users will get astropy-healpix 0.3.x and Python 3 users will get more recent versions (once released). I don't think any pinning is required? (unless regions or reproject actually started to require some newer features in astropy-healpix).

Note that if we do this we should be careful to define ``python_requires`` in ``setup.py`` to make sure that pip never accidentally installs future versions of astropy-healpix on Python 2.7.

**Comment by hugovk** [comment]
Here's the pip installs for astropy-healpix from PyPI for last month, showing low numbers for Python 2:

| category | percent | downloads |
|----------|--------:|----------:|
|        3 |  77.21% |     1,945 |
|        2 |  16.91% |       426 |
| null     |   5.88% |       148 |
| Total    |         |     2,519 |

Source: `pypistats python_major --last-month astropy-healpix`

| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  36.92% |       930 |
|      3.7 |  24.02% |       605 |
|      2.7 |  16.87% |       425 |
|      3.5 |  15.20% |       383 |
| null     |   5.88% |       148 |
|      3.4 |   1.07% |        27 |
|      2.6 |   0.04% |         1 |
| Total    |         |     2,519 |


Source: `pypistats python_minor --last-month astropy-healpix`

**Comment by hugovk** [comment]
See also https://python3statement.org/ for other projects which have pledged to drop Python 2 support in or before 2020, and for tips on how to do so.

**Comment by cdeil** [comment]
We've settled the discussion in Gammapy (see [here](https://github.com/gammapy/gammapy/blob/master/docs/development/pigs/pig-003.rst)). The plan is to drop support for Python 2 in early 2019, so given that Gammapy depends on `regions` (and thus also `astropy-healpix` now), I'd suggest that we wait a little bit, and then drop Python 2 support in Feb or March 2019, and then try to get those packages in shape for proposal / submission to Astropy core within 2019. (and not just drop Python 2 at the very last minute)

**Comment by cdeil** [comment]
We removed Python 2 support from Gammapy last week (https://github.com/gammapy/gammapy/issues/1963).

I would suggest to also remove Python 2 support now for `astropy-healpix` and for `regions`. As far as I can see the order doesn't matter really, the key is to set `python_requires>=3.5` in `setup.py`, to make sure Python 2 installs don't fetch a newer version that doesn't support Python 2 any more.

With https://github.com/asottile/pyupgrade pointed out by @hugovk it's very quick, although both `astropy-healpix` and `regions` have C extensions, so it needs some expertise / manual editing to do the cleanup.

@astrofrog and all - OK? Should we go to `>=3.5` or `>=3.6`?

Does anyone want to do it and send a PR for either package?
(I'd also be happy to do one or both soon)

**Comment by bsipocz** [comment]
How much are the above numbers coming from CI rather than from users? Is there any way to know it?

**Comment by hugovk** [comment]
It's impossible to know.

However, the Python Software Foundation's 2018 survey of over 20,000 developers from more than 150 different countries came out this week.

It shows Python 2 is clearly on the way out, especially in the field of data science.

https://pyfound.blogspot.com/2019/02/python-developers-survey-2018-results.html
https://www.jetbrains.com/research/python-developers-survey-2018/

![image](https://user-images.githubusercontent.com/1324225/52369725-02912280-2a5a-11e9-8dd2-b5a07c5ba788.png)

![image](https://user-images.githubusercontent.com/1324225/52369773-1177d500-2a5a-11e9-81a8-889e817d03c8.png)

![image](https://user-images.githubusercontent.com/1324225/52369795-1ccb0080-2a5a-11e9-872a-4aee32da5641.png)

![image](https://user-images.githubusercontent.com/1324225/52369819-28b6c280-2a5a-11e9-8f76-db10e87c5dcc.png)

**Comment by bsipocz** [comment]
Oh, I'm not worried about python2, it should go this year, period. 
I was more interested in understanding the python 3.5 vs 3.6 and 3.7 (and 3.4) numbers.

**Comment by bsipocz** [comment]
Shall we close this now, as #125 is merged?
