### ISSUE TITLE
Release 0.5?

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-healpix#133]
I need to build Python 3.8 wheels of astropy-healpix, so that I can build Python 3.8 wheels of reproject. However, I can't build Python 3.8 wheels of v0.4 of astropy-healpix as I need some changes in master. If there are no objections, I will release v0.5 of astropy-healpix shortly.

The only important issue to fix before releasing is #130

**Comment by cdeil** [comment]
👍

**Comment by astrofrog** [comment]
0.5 was released a little while back! https://pypi.org/project/astropy-healpix/0.5/
