### ISSUE TITLE
Mention astrometry.net in copyright?

### ISSUE THREAD

**Issue by olebole** [astropy/astropy-healpix#136]
Nitpicky followup to #70: Since the core code is originated in astrometry.net (although deviated far), shouldn't be mentioned astrometry.net as a copyright holder in the `License.md` file?

**Comment by astrofrog** [comment]
@dstndstn - how do you feel about this?

**Comment by dstndstn** [comment]
At the very least, you must include the LICENSE file from Astrometry.net in the 'cextern' directory.  (Otherwise you're violating term 1 of the Astrometry.net BSD license.)
