### ISSUE TITLE
Multi-order healpix example

### ISSUE THREAD

**Issue by profxj** [astropy/astropy-healpix#148]
Can someone point the way to example code for generating
a multi-order healpix object?  Either in this repo or one of LIGO's.

e.g.  my localization is a small ellipse on the sky (arcseconds) and
I wish to generate a multi-resolution sky map to describe it.

Thanks.

**Comment by lpsinger** [comment]
This is the function used by LIGO: [`ligo.skymap.moc.bayestar_adaptive_grid`](https://lscsoft.docs.ligo.org/ligo.skymap/moc/index.html#ligo.skymap.moc.bayestar_adaptive_grid)

This is the function used to write the sky map:
[`ligo.skymap.io.fits.write_sky_map`](https://lscsoft.docs.ligo.org/ligo.skymap/io/fits.html#ligo.skymap.io.fits.write_sky_map)

[mhealpy](https://mhealpy.readthedocs.io/) may also be of use to you.
