### ISSUE TITLE
Image upside down in interpolation map documentation example?

### ISSUE THREAD

**Issue by krislars** [astropy/astropy-healpix#155]
[https://github.com/astropy/astropy-healpix/blob/main/docs/interpolation.rst](https://github.com/astropy/astropy-healpix/blob/main/docs/interpolation.rst)

I think that the resulting image at the end of the Interpolating Values from a HEALPix Map documentation is upside down.  Removing the `extent=[-1, 1, -10, 10]` demonstrates that `imshow` by default starts in the upper left corner, not the lower left corner.  Adding `origin="lower"` would fix the problem.

**Comment by lpsinger** [comment]
You're right! Here's the current image, with a large and distinctive hot spot marked by an arrow:

![interpolation-1](https://user-images.githubusercontent.com/728407/133361160-82b50e83-c71d-4487-b2ae-b6fed800621a.png)

Here's a shot from Aladin, with the same hot spot marked:

![Screen Shot 2021-09-14 at 22 33 55](https://user-images.githubusercontent.com/728407/133361203-cf643d4a-b00a-4457-945a-a8e887b76664.png)

The image from the docs is supposed to be north-up, east-right; the image from Aladin is north-up, east-left, so it is to be expected that they are flipped left-right with respect to each other. But it's easy to see that they are also flipped up-down.

**Comment by krislars** [comment]
Cool!  Thanks!
