### ISSUE TITLE
Checking the 'order' argument at instantiation

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy-healpix#161]
I noticed it's possible to do, e.g. 

```python
>>> hp = HEALPix(..., order="anything")
>>> hp.neighbours(0)
```

In which case the error ``ValueError: order must be 'nested' or 'ring'`` occurs in `hp.neighbours`. Why not check this at instantiation instead?

**Comment by astrofrog** [comment]
No reason 😀 PR welcome!
