### ISSUE TITLE
ANN: Please test against astropy v5.1rc1

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-healpix#172]
Hello. You appear to be a Astropy Coordinated Package. Please report back at https://github.com/astropy/astropy/wiki/v5.1-RC-testing . Thank you!

**Comment by pllim** [comment]
v5.1 is out, so this is moot.

**Comment by lpsinger** [comment]
I did test, and it worked fine. I might have not replied because I was waiting to get the package template update merged.
