### ISSUE TITLE
Warnings in build and test

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-healpix#46]
@astrofrog - I know these are cosmetic things, not real issues. But can we try to get rid of the warnings in our build and test? I find that this helps, because then not every developer / user sees those warnings and wonders if those are real issues or not.

In the build, we have these warnings:
https://gist.github.com/cdeil/47b8441e55e957a65712f3c8d1a0e250#file-gistfile1-txt-L45
(I think I see those with every Astropy affiliated package since a few weeks or months, it must be something in Astropy or Astropy-helpers):
```
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/deil/Library/Python/3.6/lib/python/site-packages/setuptools/extension.py:9: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .monkey import get_unpatched
/Users/deil/Library/Python/3.6/lib/python/site-packages/setuptools/monkey.py:12: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .py26compat import import_module
/Users/deil/Library/Python/3.6/lib/python/site-packages/setuptools/depends.py:7: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .py33compat import Bytecode
/Users/deil/Library/Python/3.6/lib/python/site-packages/setuptools/dist.py:25: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .py36compat import Distribution_parse_config_files
/Users/deil/Library/Python/3.6/lib/python/site-packages/setuptools/msvc.py:29: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from .monkey import get_unpatched
```

And then there's this warning from healpy:
https://gist.github.com/cdeil/47b8441e55e957a65712f3c8d1a0e250#file-gistfile1-txt-L377
```
lib.macosx-10.12-x86_64-3.6/healpix/tests/test_healpy.py::test_vec2ang
  /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/healpy/pixelfunc.py:697: RuntimeWarning: invalid value encountered in true_divide
    theta = np.arccos(vectors[:,2]/dnorm)
```
Is this a case of inputs where we should also emit a warning? Or should we just suppress the warning from healpy for this case?
Do you know how to change the warning config for the tests so that we get a stacktrace containing the last line in our code that let to this warning? It would be nice to always get this info, no?

**Comment by astrofrog** [comment]
I think the ImportWarnings are a Cython bug, potentially resolved with the latest version of Cython from conda-forge: https://github.com/astropy/astropy/issues/6025#issuecomment-311483570

**Comment by astrofrog** [comment]
It looks like https://pypi.python.org/pypi/pytest-warnings has a -W option that turns all warnings into errors in case you want to see a traceback?

**Comment by astrofrog** [comment]
I think that the warning you are seeing in ``vec2ang`` is when you call it with zeros:

```python
In [4]: vec2ang(np.zeros(3))
/Users/tom/miniconda3/envs/py27/lib/python2.7/site-packages/healpy/pixelfunc.py:697: RuntimeWarning: invalid value encountered in divide
  theta = np.arccos(vectors[:,2]/dnorm)
Out[4]: (array([ nan]), array([ 0.]))
```

we use astropy.coordinates.representation which deals gracefully with this case.

**Comment by cdeil** [comment]
I think this issue was resolved at some point. I don't see these warnings any more: https://gist.github.com/cdeil/b3ac508d0c7d056e95c07bad446be674

Closing issue.
