### ISSUE TITLE
Release 0.1 ?

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-healpix#49]
@astrofrog - How about releasing v0.1 today?

I'm sure that with announcing new users / bug / feature requests will show up, and having a release 
 / conda-forge package would help e.g. with `hips`, I could switch over to `healpix` and also make a   release now.

Gammapy / reproject or other packages could then wait for a more complete and well-tested v0.2 release.

**Comment by astrofrog** [comment]
I'm happy to release today but I think we might want to rename first. I asked the coordination committee if there were any objections to using astropy-healpix and I didn't get any.

**Comment by astrofrog** [comment]
(the main issue we'll have is that ``conda install -c conda-forge healpix`` won't work because that is the C package!)

**Comment by astrofrog** [comment]
I'll be on hangouts all afternoon if we want to coordinate a release

**Comment by astrofrog** [comment]
Done!
