### ISSUE TITLE
Clarify source copyright

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy-healpix#70]
I am trying to package astropy-healpix for Debian, and so I am working on unbundling astrometry.net to instead use the [Debian astrometry.net package](https://packages.debian.org/source/buster/astrometry.net). Unfortunately, there seem to be some API differences with cextern/astrometry.net. For example, astrometry.net defines a function `healpix_get_neighboursl`, while the cextern version is called `healpixl_get_neighbours`. What is the relationship between the cextern version and the upstream version at https://github.com/dstndstn/astrometry.net?

**Comment by astrofrog** [comment]
@lpsinger - we've deliberately diverged from the astrometry.net code, so don't consider the code in astropy-healpix to be astrometry.net anymore. In that sense it probably shouldn't be in ``cextern`` anymore.

**Comment by lpsinger** [comment]
Oh, in that case, would you please just check that the [copyright file](https://salsa.debian.org/debian-astro-team/astropy-healpix/blob/master/debian/copyright) is correct?

**Comment by astrofrog** [comment]
@lpsinger - the following is incorrect as there should be no copyright to the HEALPix developers:

```
Files: *
Copyright: 2016, HEALPix developers
License: BSD-3-clause
```

and the package is now fully BSD, so the GPL license can be removed. Thanks!

**Comment by lpsinger** [comment]
> @lpsinger - the following is incorrect as there should be no copyright to the HEALPix developers:
> 
> Files: *
> Copyright: 2016, HEALPix developers
> License: BSD-3-clause

The first line of the LICENSE.md file says "Copyright (c) 2016, HEALPix developers". Would you please update it?

> and the package is now fully BSD, so the GPL license can be removed.

The GPL part refers only to the `debian` directory.

**Comment by astrofrog** [comment]
Oops yes this package used to be called healpix which was confusing and hence was renamed to astropy-healpix, so the copyright refers to the old package name. You can see why that would be confusing though, so I'll change it.

**Comment by astrofrog** [comment]
Done in https://github.com/astropy/astropy-healpix/commit/e3309684acdb8c8cebb5424716a7e57017410bea

**Comment by lpsinger** [comment]
Thanks! Last question: is the [cextern/astrometry.net/* section in the debian/copyright file](https://salsa.debian.org/debian-astro-team/astropy-healpix/blob/master/debian/copyright#L10-12) correct?

**Comment by astrofrog** [comment]
@lpsinger - yes, that looks right!

**Comment by lpsinger** [comment]
Thank you!
