### ISSUE TITLE
Implement Cython functions as Numpy ufuncs

### ISSUE THREAD

**Issue by lpsinger** [astropy/astropy-healpix#72]
This will eliminate the need for all of the manual broadcasting and type checking.

I have written [lots of examples in plain C](https://git.ligo.org/leo-singer/ligo.skymap/blob/master/src/core.c), but there are also [examples in Cython](http://www.scipy-lectures.org/advanced/advanced_numpy/#universal-functions).

**Comment by astrofrog** [comment]
That would be nice! My only hesitation is that we might lose the benefits of multi-threading? (I don't think Numpy applies ufuncs in a multi-threaded way?)

**Comment by lpsinger** [comment]
> My only hesitation is that we might lose the benefits of multi-threading? (I don't think Numpy applies ufuncs in a multi-threaded way?)

Sure, you can run ufuncs in multithreaded code. Nothing stops you from releasing the GIL inside your ufunc loop function.

**Comment by lpsinger** [comment]
Actually, looking at the Numpy source code, I kind of think that Numpy itself releases the GIL while it is calling your ufunc loop function.

**Comment by astrofrog** [comment]
@lpsinger - ok cool!
