### ISSUE TITLE
Add support for uniq pixel ID scheme

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-healpix#91]
This HEALPix "unique identifier scheme" is starting to be used widely:
- see section 3.2 in http://healpix.sourceforge.net/pdf/intro.pdf
- see section 2.3.1 in http://ivoa.net/documents/MOC/

It's used in MOC, but also in Gammapy we want to use it for multi-resolution maps, and I see @lpsinger is already using it in LIGO (see [slides](https://dcc.ligo.org/public/0149/G1800186/003/healpix-multiresolution.pdf)), so IMO we should support it in `astropy.healpix`.

We can discuss about deeper integration, but a first step is to add converter functions.
@tboch already added a Numpy implementation in https://github.com/cds-astro/mocpy/blob/5bbdf1093b25a597e996d5087f8046354e26edf7/mocpy/utils.py#L4

```python
def uniq2orderipix(uniq):
    order = ((np.log2(uniq//4)) // 2)
    order = order.astype(int)
    ipix = uniq - 4 * (4**order)
    return order, ipix

def orderipix2uniq(n_order, n_pix):
    return n_pix + ((4**n_order) << 2)
```

@tboch or @bmatthieu3 - Do you have time to add a copy here in `astropy-healpix`? If no, I could make a PR later this week as well.

Eventually this should be re-implemented in C for maximum speed / memory usage (avoiding temp array copies), but I think for now adding this implementation here with a docstring and test would good.

**Comment by cdeil** [comment]
If we code those functions with `order` as input (or in any case) IMO we should also add this helper:
```python
def nside2order(nside):
    return np.log2(nside).astype(int)
```
It works up to `nside=63`.

**Comment by astrofrog** [comment]
@cdeil - I agree, though I think we should include a ``round`` kwarg as for ``pixel_resolution_to_nside``

**Comment by cdeil** [comment]
After thinking about this a bit more, I'd suggest to add those as standalone helper functions for now.

Deeper integration (i.e. taking `uniq` instead of the seprate `(nside, ipix)` in the existing API can be proposed / discussed, but that's a big maybe; whereas adding support via these helper functions is an immediate and clear improvement.

**Comment by cdeil** [comment]
Added by @bmatthieu3 in #105 .
