### ISSUE TITLE
Expose a third XY indexing scheme

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-healpix#96]
I think in addition to the current `scheme : { ‘nested’ | ‘ring’ }` we should expose a third one: "xy".

Technically it's very simple, internally we always go via "xy" already:
https://github.com/astropy/astropy-healpix/blob/ad18b81e5adad54d23ea78b5d167c3a733a1dcf7/cextern/astrometry.net/healpix.h#L101

I think it would be useful e.g. for working with HiPS. @tboch - Is that true? Or is supporting HEALPix to HiPS tile X/Y position matching very simple already even without this?

@astrofrog @dstndstn @lpsinger - Thoughts?

**Comment by tboch** [comment]
@cdeil : I'd like to discuss this in details next week with you. I'm not 100% sure this would allow for easy HEALPix to HiPS pixel position mapping.

**Comment by cdeil** [comment]
@tboch @adonath - I think the conclusion of our discussions was that "xy" index isn't something users need? Specifically for the task of HEALPix map <-> HiPS tile conversion using [hips_tile_healpix_ipix_array](https://github.com/hipspy/hips/blob/8d6078ffb08f2fd1e63e54b305b5b336db8f535c/hips/utils/healpix.py#L125) does the job with good enough performance? And besides that, given that no-one is using "xy" indexing e.g. for maps or other things where efficient indexing or reorder is needed, we shouldn't expose it in `astropy-healpix` as a third indexing ordering?

Do you agree? Close issue?

**Comment by tboch** [comment]
@cdeil: yes, I agree with your summary.
